//ecma script
//european computer manufacturers association 
//ES6 or  ecmascript 2015 is 6th and major edition of  ecmascript language specification standard .
//it defines the standard for implementation of javascript.
//it brought new features like let and const keyword and rest and spread operators,classes,modules ,template literals
// to make js easier and fun to use

// ES6 FEATURE:
// 1.let and const
// 2.Arrow function
// 3.Default parameters
// 4.template literals and multiline SVGStringList
// 5.destructuring
// 6.higher order function
// 7.promises
// 8.classes
// 9.modules


//variables decleared with var keywored are not blocked scope they are function scoped

// var b=30;
// if(b==30){
//     var c=40;
//     console.log(c)
// }
// console.log(c)


// function test(){
//     var d=90
//     console.log(d)
// }
// test()
// console.log(d)
//   ----------------


if(true){
    let e=40;
    console.log(e)
}
// e=20;
console.log(e)





